modLoader="javafml"

loaderVersion="[1,)"

license="MIT"

issueTrackerURL="https://github.com/Mangopill/Customized/issues"

[[mods]]
modId="customized"

version="1.21.1-neoforge-1.0.0"

displayName="Customized"

logoFile="pack.png"

authors="Mangopill"

description='''Customized Cooking Experience.'''

#[[mixins]]
#config="customized.mixins.json"

#[[accessTransformers]]

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.customized]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.customized]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"
