@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mangopill.customized.common.effect;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;