@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mangopill.customized.client.event.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;