@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mangopill.customized.common.effect.powerful;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;