@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mangopill.customized.client.event.player;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;