@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mangopill.customized.client.event;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;