@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mangopill.customized.common.block.capabilities;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;