@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mangopill.customized.integration.curios.common.item;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;