@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mangopill.customized.client.util.strategy;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;