@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mangopill.customized.client.particle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;