@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mangopill.customized.integration.jei;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;