@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mangopill.customized.common.entity.projectile;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;