@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mangopill.customized.integration.jei.ingredient;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;