@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mangopill.customized.common.effect.normal;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;